name: Storybook Build & Deployment at Github Page

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  storybook-ci-cd:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ROOT_SPHERE_GITHUB_TOKEN }}
      PUBLIC_NPM_TOKEN: ${{secrets.PUBLIC_NPM_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha != '' && github.event.inputs.sha || github.sha }}

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Packages
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Build Storybook
        run: pnpm run build:storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/components/docs
